version: '3.8'

services:
  oneflow-ai:
    build: .
    container_name: oneflow-ai
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - STABILITY_API_KEY=${STABILITY_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - DATABASE_URL=postgresql://oneflow:oneflow@postgres:5432/oneflow
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-change-me-in-production}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: oneflow-postgres
    environment:
      - POSTGRES_USER=oneflow
      - POSTGRES_PASSWORD=oneflow
      - POSTGRES_DB=oneflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oneflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
