version: '3.8'

services:
  # ============================================================================
  # PROMETHEUS - Metrics Collection
  # ============================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: oneflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # GRAFANA - Visualization
  # ============================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: oneflow-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # JAEGER - Distributed Tracing
  # ============================================================================
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: oneflow-jaeger
    ports:
      - "5775:5775/udp"     # Zipkin
      - "6831:6831/udp"     # Compact thrift
      - "6832:6832/udp"     # Binary thrift
      - "5778:5778"         # Serve configs
      - "16686:16686"       # UI
      - "14268:14268"       # Jaeger collector
      - "14250:14250"       # gRPC
      - "9411:9411"         # Zipkin
      - "4317:4317"         # OTLP gRPC
      - "4318:4318"         # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    volumes:
      - jaeger_data:/tmp
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # OPENTELEMETRY COLLECTOR
  # ============================================================================
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: oneflow-otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check
    depends_on:
      - jaeger
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # LOKI - Log Aggregation
  # ============================================================================
  loki:
    image: grafana/loki:latest
    container_name: oneflow-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # PROMTAIL - Log Shipper
  # ============================================================================
  promtail:
    image: grafana/promtail:latest
    container_name: oneflow-promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - ../logs:/var/lib/oneflow/logs:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # ALERTMANAGER - Alert Management
  # ============================================================================
  alertmanager:
    image: prom/alertmanager:latest
    container_name: oneflow-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # NODE EXPORTER - System Metrics
  # ============================================================================
  node-exporter:
    image: prom/node-exporter:latest
    container_name: oneflow-node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    networks:
      - monitoring

  # ============================================================================
  # CADVISOR - Container Metrics
  # ============================================================================
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: oneflow-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  jaeger_data:
  loki_data:
  alertmanager_data:
