apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneflow
spec:
  rules:
    - host: oneflow.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: oneflow
              port:
                number: 80
