apiVersion: v1
kind: Service
metadata:
  name: oneflow-ai
  namespace: oneflow-ai
  labels:
    app: oneflow-ai
    component: api
  annotations:
    # Аннотации для cloud load balancer (если используется LoadBalancer)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    # Prometheus
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 часа для WebSocket
  
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  
  selector:
    app: oneflow-ai
    component: api

---
# Headless Service для StatefulSet (если потребуется)
apiVersion: v1
kind: Service
metadata:
  name: oneflow-ai-headless
  namespace: oneflow-ai
  labels:
    app: oneflow-ai
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: oneflow-ai
