name: 📝 Documentation Issue
description: Report a documentation issue or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear explanation
        - Broken link
        - Typo/grammar
        - Example code not working
        - Translation issue
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - Page URL: https://docs.oneflow.ai/...
        - Section: Getting Started > Installation
        - File: docs/api/authentication.md
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the documentation currently say? (copy/paste or screenshot)
      placeholder: Current text or screenshot...
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Improvement
      description: What should the documentation say instead?
      placeholder: Suggested correction or improvement...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: Why is this confusing? What were you trying to do?

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
